# Esto es para gestionar las tablas

spring.jpa.hibernate.ddl-auto=update 

#indicar la ruta de la base de datos

spring.datasource.url=jdbc:mysql://localhost:3306/agencia_viajes

#indicar el usuario de la base de datos

spring.datasource.username=root

#indicar la clave del usuario

spring.datasource.password=Jh0n4t4n*28*

#Usar el driver mySql

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

server.port=8081

spring.thymeleaf.cache=false



logging.level.org.springframework.web.servlet.DispatcherServlet=TRACE

logging.level.org.springframework.web.filter=TRACE

spring.servlet.multipart.enabled=true

spring.servlet.multipart.max-file-size=10MB

spring.servlet.multipart.max-request-size=10MB



logging.level.org.springframework.web=DEBUG


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tu correo
spring.mail.password=tu clave de 16 digitos 
eliminar despues de generar la clave
https://accounts.google.com/v3/signin/challenge/pk/presend?TL=ANzgctSALlLKlLVnmxRlApACAUQaIE91_L3V73lf2GOczXCq3VxPfg-I1XX-T3YQ&authuser=0&cid=1&continue=https%3A%2F%2Fmyaccount.google.com%2Fapppasswords&dsh=S-1490819332%3A1763017177155991&flowName=GlifWebSignIn&followup=https%3A%2F%2Fmyaccount.google.com%2Fapppasswords&ifkv=ARESoU19m0IRr8Il4a9Eg87xNeW2VIOnul1zuXmnNwN2iWw_why3QnD_S1bGYUA7uw5rjvkQTY8O&osid=1&rart=ANgoxccC4BQX2f_EFdUFBnlKjO-eby0Pn7GXodQ9mWV8u3iLphjdI5mTrEvW2azuY4NgMwfVr2YsNcOWN7lfzMQZUPjIyfZUoX4fNZXKVQsp3Ek0Mc6cDVg&rpbg=1&service=accountsettings
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true